/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicAuthRouteImport } from './routes/_public/_auth'
import { Route as PublicMenuRouteImport } from './routes/_public/menu'
import { Route as PublicOrdersRouteImport } from './routes/_public/orders'
import { Route as ManageAnalyticsRouteImport } from './routes/manage/analytics'
import { Route as ManageDashboardRouteImport } from './routes/manage/dashboard'
import { Route as ManageDishesRouteImport } from './routes/manage/dishes'
import { Route as ManageKitchenRouteImport } from './routes/manage/kitchen'
import { Route as ManageOrdersRouteImport } from './routes/manage/orders'
import { Route as ManageStaffsRouteImport } from './routes/manage/staffs'
import { Route as ManageTablesRouteImport } from './routes/manage/tables'
import { Route as PublicAuthLoginRouteImport } from './routes/_public/_auth/login'
import { Route as PublicAuthSignupRouteImport } from './routes/_public/_auth/signup'
import { Route as PublicGuestTablesTableNumberRouteImport } from './routes/_public/guest/tables/$tableNumber'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthRoute = PublicAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => PublicRoute,
} as any)
const PublicMenuRoute = PublicMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => PublicRoute,
} as any)
const PublicOrdersRoute = PublicOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => PublicRoute,
} as any)
const ManageAnalyticsRoute = ManageAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ManageRoute,
} as any)
const ManageDashboardRoute = ManageDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ManageRoute,
} as any)
const ManageDishesRoute = ManageDishesRouteImport.update({
  id: '/dishes',
  path: '/dishes',
  getParentRoute: () => ManageRoute,
} as any)
const ManageKitchenRoute = ManageKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => ManageRoute,
} as any)
const ManageOrdersRoute = ManageOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ManageRoute,
} as any)
const ManageStaffsRoute = ManageStaffsRouteImport.update({
  id: '/staffs',
  path: '/staffs',
  getParentRoute: () => ManageRoute,
} as any)
const ManageTablesRoute = ManageTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => ManageRoute,
} as any)
const PublicAuthLoginRoute = PublicAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicAuthRoute,
} as any)
const PublicAuthSignupRoute = PublicAuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => PublicAuthRoute,
} as any)
const PublicGuestTablesTableNumberRoute =
  PublicGuestTablesTableNumberRouteImport.update({
    id: '/guest/tables/$tableNumber',
    path: '/guest/tables/$tableNumber',
    getParentRoute: () => PublicRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/manage': typeof ManageRouteWithChildren
  '/menu': typeof PublicMenuRoute
  '/orders': typeof PublicOrdersRoute
  '/manage/analytics': typeof ManageAnalyticsRoute
  '/manage/dashboard': typeof ManageDashboardRoute
  '/manage/dishes': typeof ManageDishesRoute
  '/manage/kitchen': typeof ManageKitchenRoute
  '/manage/orders': typeof ManageOrdersRoute
  '/manage/staffs': typeof ManageStaffsRoute
  '/manage/tables': typeof ManageTablesRoute
  '/login': typeof PublicAuthLoginRoute
  '/signup': typeof PublicAuthSignupRoute
  '/guest/tables/$tableNumber': typeof PublicGuestTablesTableNumberRoute
}
export interface FileRoutesByTo {
  '/manage': typeof ManageRouteWithChildren
  '/': typeof PublicIndexRoute
  '/menu': typeof PublicMenuRoute
  '/orders': typeof PublicOrdersRoute
  '/manage/analytics': typeof ManageAnalyticsRoute
  '/manage/dashboard': typeof ManageDashboardRoute
  '/manage/dishes': typeof ManageDishesRoute
  '/manage/kitchen': typeof ManageKitchenRoute
  '/manage/orders': typeof ManageOrdersRoute
  '/manage/staffs': typeof ManageStaffsRoute
  '/manage/tables': typeof ManageTablesRoute
  '/login': typeof PublicAuthLoginRoute
  '/signup': typeof PublicAuthSignupRoute
  '/guest/tables/$tableNumber': typeof PublicGuestTablesTableNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/manage': typeof ManageRouteWithChildren
  '/_public/_auth': typeof PublicAuthRouteWithChildren
  '/_public/menu': typeof PublicMenuRoute
  '/_public/orders': typeof PublicOrdersRoute
  '/manage/analytics': typeof ManageAnalyticsRoute
  '/manage/dashboard': typeof ManageDashboardRoute
  '/manage/dishes': typeof ManageDishesRoute
  '/manage/kitchen': typeof ManageKitchenRoute
  '/manage/orders': typeof ManageOrdersRoute
  '/manage/staffs': typeof ManageStaffsRoute
  '/manage/tables': typeof ManageTablesRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/_auth/login': typeof PublicAuthLoginRoute
  '/_public/_auth/signup': typeof PublicAuthSignupRoute
  '/_public/guest/tables/$tableNumber': typeof PublicGuestTablesTableNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/manage'
    | '/menu'
    | '/orders'
    | '/manage/analytics'
    | '/manage/dashboard'
    | '/manage/dishes'
    | '/manage/kitchen'
    | '/manage/orders'
    | '/manage/staffs'
    | '/manage/tables'
    | '/login'
    | '/signup'
    | '/guest/tables/$tableNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/manage'
    | '/'
    | '/menu'
    | '/orders'
    | '/manage/analytics'
    | '/manage/dashboard'
    | '/manage/dishes'
    | '/manage/kitchen'
    | '/manage/orders'
    | '/manage/staffs'
    | '/manage/tables'
    | '/login'
    | '/signup'
    | '/guest/tables/$tableNumber'
  id:
    | '__root__'
    | '/_public'
    | '/manage'
    | '/_public/_auth'
    | '/_public/menu'
    | '/_public/orders'
    | '/manage/analytics'
    | '/manage/dashboard'
    | '/manage/dishes'
    | '/manage/kitchen'
    | '/manage/orders'
    | '/manage/staffs'
    | '/manage/tables'
    | '/_public/'
    | '/_public/_auth/login'
    | '/_public/_auth/signup'
    | '/_public/guest/tables/$tableNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  ManageRoute: typeof ManageRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/_auth': {
      id: '/_public/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicAuthRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/menu': {
      id: '/_public/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof PublicMenuRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/orders': {
      id: '/_public/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof PublicOrdersRouteImport
      parentRoute: typeof PublicRoute
    }
    '/manage/analytics': {
      id: '/manage/analytics'
      path: '/analytics'
      fullPath: '/manage/analytics'
      preLoaderRoute: typeof ManageAnalyticsRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/dashboard': {
      id: '/manage/dashboard'
      path: '/dashboard'
      fullPath: '/manage/dashboard'
      preLoaderRoute: typeof ManageDashboardRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/dishes': {
      id: '/manage/dishes'
      path: '/dishes'
      fullPath: '/manage/dishes'
      preLoaderRoute: typeof ManageDishesRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/kitchen': {
      id: '/manage/kitchen'
      path: '/kitchen'
      fullPath: '/manage/kitchen'
      preLoaderRoute: typeof ManageKitchenRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/orders': {
      id: '/manage/orders'
      path: '/orders'
      fullPath: '/manage/orders'
      preLoaderRoute: typeof ManageOrdersRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/staffs': {
      id: '/manage/staffs'
      path: '/staffs'
      fullPath: '/manage/staffs'
      preLoaderRoute: typeof ManageStaffsRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/tables': {
      id: '/manage/tables'
      path: '/tables'
      fullPath: '/manage/tables'
      preLoaderRoute: typeof ManageTablesRouteImport
      parentRoute: typeof ManageRoute
    }
    '/_public/_auth/login': {
      id: '/_public/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicAuthLoginRouteImport
      parentRoute: typeof PublicAuthRoute
    }
    '/_public/_auth/signup': {
      id: '/_public/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof PublicAuthSignupRouteImport
      parentRoute: typeof PublicAuthRoute
    }
    '/_public/guest/tables/$tableNumber': {
      id: '/_public/guest/tables/$tableNumber'
      path: '/guest/tables/$tableNumber'
      fullPath: '/guest/tables/$tableNumber'
      preLoaderRoute: typeof PublicGuestTablesTableNumberRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicAuthRouteChildren {
  PublicAuthLoginRoute: typeof PublicAuthLoginRoute
  PublicAuthSignupRoute: typeof PublicAuthSignupRoute
}

const PublicAuthRouteChildren: PublicAuthRouteChildren = {
  PublicAuthLoginRoute: PublicAuthLoginRoute,
  PublicAuthSignupRoute: PublicAuthSignupRoute,
}

const PublicAuthRouteWithChildren = PublicAuthRoute._addFileChildren(
  PublicAuthRouteChildren,
)

interface PublicRouteChildren {
  PublicAuthRoute: typeof PublicAuthRouteWithChildren
  PublicMenuRoute: typeof PublicMenuRoute
  PublicOrdersRoute: typeof PublicOrdersRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicGuestTablesTableNumberRoute: typeof PublicGuestTablesTableNumberRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAuthRoute: PublicAuthRouteWithChildren,
  PublicMenuRoute: PublicMenuRoute,
  PublicOrdersRoute: PublicOrdersRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicGuestTablesTableNumberRoute: PublicGuestTablesTableNumberRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface ManageRouteChildren {
  ManageAnalyticsRoute: typeof ManageAnalyticsRoute
  ManageDashboardRoute: typeof ManageDashboardRoute
  ManageDishesRoute: typeof ManageDishesRoute
  ManageKitchenRoute: typeof ManageKitchenRoute
  ManageOrdersRoute: typeof ManageOrdersRoute
  ManageStaffsRoute: typeof ManageStaffsRoute
  ManageTablesRoute: typeof ManageTablesRoute
}

const ManageRouteChildren: ManageRouteChildren = {
  ManageAnalyticsRoute: ManageAnalyticsRoute,
  ManageDashboardRoute: ManageDashboardRoute,
  ManageDishesRoute: ManageDishesRoute,
  ManageKitchenRoute: ManageKitchenRoute,
  ManageOrdersRoute: ManageOrdersRoute,
  ManageStaffsRoute: ManageStaffsRoute,
  ManageTablesRoute: ManageTablesRoute,
}

const ManageRouteWithChildren =
  ManageRoute._addFileChildren(ManageRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  ManageRoute: ManageRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
